apiVersion: apps/v1
kind: Deployment
metadata:
  name: ser2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ser2
  template:
    metadata:
      labels:
        app: ser2
    spec:
      containers:
        - name: server
          image: naresh2026/repo1:ser2
          #imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: WEBSOCKET_ALLOWED_ORIGINS
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: ser2-service
spec:
  type: NodePort
  selector:
    app: ser2
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083  # Minikube will expose this service
